BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS clients (id INTEGER PRIMARY KEY AUTOINCREMENT,nom TEXT NOT NULL,prenom TEXT NOT NULL,cin TEXT UNIQUE NOT NULL,telephone TEXT,email TEXT);
CREATE TABLE IF NOT EXISTS reservations (id INTEGER PRIMARY KEY AUTOINCREMENT,clientId INTEGER NOT NULL,voitureId INTEGER NOT NULL,dateDebut TEXT NOT NULL,dateFin TEXT NOT NULL,montantTotal REAL NOT NULL,statut TEXT DEFAULT 'EN_COURS',FOREIGN KEY (clientId) REFERENCES clients(id),FOREIGN KEY (voitureId) REFERENCES voitures(id));
CREATE TABLE IF NOT EXISTS voitures (id INTEGER PRIMARY KEY AUTOINCREMENT,marque TEXT NOT NULL,modele TEXT NOT NULL,immatriculation TEXT UNIQUE NOT NULL,categorie TEXT,prixParJour REAL NOT NULL,statut TEXT DEFAULT 'DISPONIBLE');
COMMIT;
